name: Ensure Advanced PR Templates
description: Creates or updates multiple pull request templates with dynamic content and validation
inputs:
  templates:
    description: 'YAML array of template objects: [{name: feature.md, content: ...}, ...]'
    required: true
  overwrite:
    description: 'Overwrite existing templates (true/false)'
    required: false
    default: 'false'
  inject-date:
    description: 'Inject current date (true/false)'
    required: false
    default: 'false'
  inject-author:
    description: 'Inject author from GITHUB_ACTOR (true/false)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p .github/PULL_REQUEST_TEMPLATE
        echo "Parsing templates input..."
        echo "${{ inputs.templates }}" > templates.yaml
        python3 <<EOF
import os, yaml, datetime
with open('templates.yaml') as f:
    templates = yaml.safe_load(f)
for t in templates:
    name = t.get('name')
    content = t.get('content', '')
    if os.environ.get('INPUT_INJECT_DATE', 'false').lower() == 'true':
        content = content.replace('{{DATE}}', datetime.datetime.utcnow().strftime('%Y-%m-%d'))
    if os.environ.get('INPUT_INJECT_AUTHOR', 'false').lower() == 'true':
        content = content.replace('{{AUTHOR}}', os.environ.get('GITHUB_ACTOR', 'unknown'))
    path = f".github/PULL_REQUEST_TEMPLATE/{name}"
    if os.path.exists(path) and os.environ.get('INPUT_OVERWRITE', 'false').lower() != 'true':
        print(f"{path} exists. Skipping (overwrite disabled).")
        continue
    # Validation: must have Description and Checklist
    if 'Description' not in content or 'Checklist' not in content:
        print(f"Warning: {name} missing required sections.")
    with open(path, 'w') as out:
        out.write(content)
    print(f"Created/updated {path}")
EOF
      shell: bash
