name: "Feature Request"
description: "Suggest a new feature or enhancement"
title: "✨ Feature: [Brief Description]"
labels:
  - enhancement
  - feature-request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.
  
  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of the feature you'd like to see"
      placeholder: "Describe the feature and what it should do"
    validations:
      required: true
  
  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve?"
      placeholder: "Describe the problem or pain point this feature addresses"
    validations:
      required: true
  
  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "How do you think this feature should work?"
      placeholder: "Describe your proposed solution in detail"
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternative solutions?"
      placeholder: "Describe any alternative solutions you've considered"
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my workflow"
        - "Critical - Blocking my work"
      default: 1
    validations:
      required: true
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any additional context, mockups, or examples"
      placeholder: "Add any other context, screenshots, or examples here"
    validations:
      required: false
