name: "Repo Creation Workflow"
description: "Tracks the main repo‐creation task and its sub-issues"
title: "🔧 Repo Creation Workflow – [short description]"
labels:
  - automation
  - workflow
body:
  - type: markdown
    attributes:
      value: |
        Use this template to break down the {{issue.title}} work into discrete sub-issues.
  - type: checkboxes
    attributes:
      options:
        - label: "Parent issue: #1 Automate repository creation via GitHub Actions"
          name: parent_issue
        - label: "#1.1 Define and validate workflow inputs (repo_name, description, visibility)"
          name: define_inputs
        - label: "#1.2 Implement the “create repo” logic (GitHub REST API or gh CLI)"
          name: implement_logic
        - label: "#1.3 Initialize default files (README, .gitignore, LICENSE)"
          name: init_defaults
        - label: "#1.4 Apply branch protection, labels, and topics via a settings action"
          name: apply_protections
        - label: "#1.5 Secure and scope the token (secret management, least‐privilege scopes)"
          name: secure_token
        - label: "#1.6 End-to-end testing and documentation"
          name: testing_docs
