name: "Security Enhancement"
description: "For security-related improvements and configurations"
title: "🔒 Security: [Security Feature]"
labels:
  - security
  - compliance
  - enhancement
body:
  - type: dropdown
    id: security_type
    attributes:
      label: "Security Type"
      description: "What type of security enhancement is this?"
      options:
        - "Code Scanning (CodeQL)"
        - "Secret Scanning"
        - "Dependency Scanning"
        - "Branch Protection"
        - "Access Control"
        - "Security Policies"
        - "Vulnerability Management"
      default: 0
    validations:
      required: true
  
  - type: textarea
    id: security_description
    attributes:
      label: "Security Enhancement Description"
      description: "Describe the security improvement needed"
      placeholder: "What security issue needs to be addressed or what enhancement should be implemented?"
    validations:
      required: true
  
  - type: textarea
    id: compliance_requirements
    attributes:
      label: "Compliance Requirements"
      description: "Any compliance standards this addresses"
      placeholder: "e.g., SOC 2, GDPR, internal security policies"
    validations:
      required: false
  
  - type: textarea
    id: implementation_steps
    attributes:
      label: "Implementation Steps"
      description: "High-level steps to implement this security enhancement"
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: false
