name: "Workflow Implementation"
description: "For implementing specific GitHub Actions workflows"
title: "⚙️ Workflow: [Workflow Name]"
labels:
  - github-actions
  - workflow
  - automation
body:
  - type: input
    id: workflow_name
    attributes:
      label: "Workflow Name"
      description: "Name of the workflow to implement"
      placeholder: "e.g., Repository Creation Automation"
    validations:
      required: true
  
  - type: dropdown
    id: trigger_type
    attributes:
      label: "Trigger Type"
      description: "How should this workflow be triggered?"
      options:
        - "workflow_dispatch (manual)"
        - "push to main"
        - "pull_request"
        - "schedule (cron)"
        - "issue events"
        - "release events"
      default: 0
    validations:
      required: true
  
  - type: textarea
    id: workflow_description
    attributes:
      label: "Workflow Description"
      description: "What should this workflow do?"
      placeholder: "Describe the workflow's purpose and steps"
    validations:
      required: true
  
  - type: textarea
    id: inputs_outputs
    attributes:
      label: "Inputs & Outputs"
      description: "What inputs does it need and what outputs does it produce?"
      placeholder: |
        **Inputs:**
        - input1: description
        - input2: description
        
        **Outputs:**
        - output1: description
        - output2: description
    validations:
      required: false
  
  - type: textarea
    id: permissions_required
    attributes:
      label: "Permissions Required"
      description: "What GitHub permissions does this workflow need?"
      placeholder: |
        - contents: write
        - issues: write
        - pull-requests: write
    validations:
      required: false
