name: Ensure Advanced PR Templates

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main, 'feature/*']
  schedule:
    - cron: '0 3 * * 1'

jobs:
  ensure-pr-templates-advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PyYAML
        run: pip install pyyaml
      - uses: ./.github/actions/ensure-pr-templates-advanced
        with:
          templates: |
            - name: feature.md
              content: |
                # Feature Pull Request
                
                ## Description
                Please describe the new feature and its motivation.
                
                ## Type of Feature
                - [ ] New functionality
                - [ ] Enhancement to existing feature
                - [ ] Performance improvement
                - [ ] User experience improvement
                
                ## Checklist
                - [ ] Code follows style guidelines
                - [ ] Tests added/updated
                - [ ] Documentation updated
                - [ ] Breaking changes documented
                - [ ] Backward compatibility maintained
                
                ## Testing
                - [ ] Unit tests pass
                - [ ] Integration tests pass
                - [ ] Manual testing completed
                
                ## Date: {{DATE}}
                ## Author: {{AUTHOR}}
            - name: bugfix.md
              content: |
                # Bugfix Pull Request
                
                ## Description
                Please describe the bug and how it was fixed.
                
                ## Bug Details
                - **Severity**: [ ] Critical [ ] High [ ] Medium [ ] Low
                - **Environment**: [ ] Production [ ] Staging [ ] Development
                - **Affected Users**: [ ] All [ ] Some [ ] None
                
                ## Root Cause
                Brief explanation of what caused the bug.
                
                ## Solution
                Brief explanation of how the bug was fixed.
                
                ## Checklist
                - [ ] Bug is reproducible
                - [ ] Fix is covered by tests
                - [ ] Documentation updated
                - [ ] Regression tests added
                - [ ] Manual verification completed
                
                ## Date: {{DATE}}
                ## Author: {{AUTHOR}}
            - name: hotfix.md
              content: |
                # Hotfix Pull Request
                
                ## Description
                Critical issue requiring immediate deployment.
                
                ## Urgency Level
                - [ ] Critical - Production down
                - [ ] High - Major functionality broken
                - [ ] Medium - Minor functionality issue
                
                ## Impact Assessment
                - **Users Affected**: 
                - **Systems Affected**: 
                - **Downtime Expected**: 
                
                ## Rollback Plan
                - [ ] Rollback procedure documented
                - [ ] Database changes are reversible
                - [ ] Config changes documented
                
                ## Checklist
                - [ ] Issue is critical and requires immediate fix
                - [ ] Fix has been tested in similar environment
                - [ ] Monitoring is in place
                - [ ] Team lead approval obtained
                - [ ] Stakeholders notified
                
                ## Date: {{DATE}}
                ## Author: {{AUTHOR}}
            - name: documentation.md
              content: |
                # Documentation Pull Request
                
                ## Description
                Updates to project documentation.
                
                ## Type of Documentation
                - [ ] API documentation
                - [ ] User guide
                - [ ] Developer guide
                - [ ] README updates
                - [ ] Code comments
                - [ ] Architecture documentation
                
                ## Changes Made
                - [ ] Added new documentation
                - [ ] Updated existing documentation
                - [ ] Fixed documentation errors
                - [ ] Removed outdated documentation
                
                ## Checklist
                - [ ] Documentation is accurate and up-to-date
                - [ ] Links are working
                - [ ] Examples are tested
                - [ ] Grammar and spelling checked
                - [ ] Consistent formatting applied
                
                ## Date: {{DATE}}
                ## Author: {{AUTHOR}}
          overwrite: 'true'
          inject-date: 'true'
          inject-author: 'true'
