name: Main Repository Automation

on:
  workflow_dispatch:
    inputs:
      skip_security:
        description: 'Skip security features setup'
        required: false
        default: false
        type: boolean

concurrency:
  group: main-automation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ensure-codeowners:
    uses: ./.github/workflows/ensure-codeowners.yml
    secrets: inherit

  ensure-dependabot:
    uses: ./.github/workflows/ensure-dependabot.yml
    secrets: inherit

  ensure-pr-template:
    uses: ./.github/workflows/ensure-pr-template.yml
    secrets: inherit

  ensure-pr-templates-advanced:
    uses: ./.github/workflows/ensure-pr-templates-advanced.yml
    needs: ensure-pr-template
    secrets: inherit

  enable-all-security-features:
    if: ${{ inputs.skip_security != 'true' }}
    uses: ./.github/workflows/enable-all-security-features.yml
    needs: [ensure-codeowners, ensure-dependabot, ensure-pr-template, ensure-pr-templates-advanced]
    secrets: inherit

  verify-security-status:
    if: ${{ inputs.skip_security != 'true' }}
    uses: ./.github/workflows/verify-security-status.yml
    needs: enable-all-security-features
    secrets: inherit
