name: "Security Scan #5"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeql-analysis:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          # Include languages present in this repository; scanning YAML workflows
          languages: 'yaml'

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
